backend/controllers/BelongingController.php
<?php

namespace backend\controllers;

use backend\models\catalog\Belonging;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BelongingController implements the CRUD actions for Belonging model.
 */
class BelongingController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Belonging models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Belonging::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Belonging model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Belonging();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Belonging model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Belonging model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Belonging model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Belonging the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Belonging::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/BelongingController.php
<?php

namespace frontend\controllers;

use frontend\models\catalog\Belonging;
use frontend\models\catalog\Category;
use frontend\models\catalog\ProductSearch;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;

/**
 * BelongingController implements the CRUD actions for Belonging model.
 */
class BelongingController extends Controller
{
    public $parents;
    public $children;
    public $layout = 'category';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Belonging models.
     * @return mixed
     */
    public function actionIndex($belonging_id, $category_id = 0, $sort = 'created_at'){
        $belonging = Belonging::findOne($belonging_id);
        $belongings = Belonging::find()->all();
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->where(['belonging_id' => $belonging_id, 'status' => '1']);
        $dataProvider->sort->enableMultiSort = true;
        $dataProvider->setSort([
            'defaultOrder' => [
                'stock' => SORT_DESC,
                $sort => SORT_DESC
            ]
        ]);
        $dataProvider->pagination->pageSize = 21;

        if ($category_id){
            $category = Category::findOne($category_id);

            if ($category->parent_id){
                $this->findCategoryParents($category->parent_id);
                $parents = array_reverse($this->parents);
            }else{
                $parents = false;
            }
            $this->findCategoryChildren($category_id);
            $query = "(`category_id` = '{$category_id}' AND `belonging_id` = '{$belonging_id}')";
            if ($this->children){
                foreach ($this->children as $child){
                    $query .= " OR (`category_id` = '" . $child['id'] . "' AND `belonging_id` = '{$belonging_id}')";
                }
            }

            $dataProvider->query->where($query);
        }else{
            $category = false;
            $parents = false;
        }

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'belonging' => $belonging,
            'belongings' => $belongings,
            'category' => $category,
            'parents' => $parents,
            'children' => $this->children,
        ]);
    }
    public function findCategoryParents($c){
        $category = Category::findOne($c);
        $this->parents[] = [
            'id' => $category->id,
            'name' => $category->name,
            'meta_h1' => $category->meta_h1,
            'meta_t' => $category->meta_t,
            'url' => $category->url,
        ];
        if ($category->parent_id)
            $this->findCategoryParents($category->parent_id);
    }
    public function findCategoryChildren($c){
        $child = Category::findOne(['parent_id' => $c]);
        if (!is_null($child)){
            $this->children[] = [
                'id' => $child->id,
                'name' => $child->name,
                'meta_h1' => $child->meta_h1,
                'meta_t' => $child->meta_t,
                'url' => $child->url,
            ];
            $this->findCategoryChildren($child->id);
        }
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use backend\classes\SortList;
use common\models\CustomerLoginForm;
use frontend\models\catalog\Belonging;
use frontend\models\catalog\Category;
use frontend\models\catalog\ProductSearch;
use frontend\models\catalog\Supply;
use frontend\models\module\CallMe;
use frontend\models\shop\Currency;
use frontend\models\shop\Manager;
use frontend\models\shop\Shipping;
use frontend\models\SignupForm;
use Yii;
use yii\base\InvalidParamException;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use yii\web\HttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $layout = 'main';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }


    public function actionLogin() {
        if (Yii::$app->request->isAjax) {
            $model = new CustomerLoginForm();
            if ($model->load(Yii::$app->request->post())) {
                if ($model->login()) {
                    $return_url = Yii::$app->request->referrer;

                    if($return_url!=NULL){
                        return $this->redirect($return_url);
                    }
                    else{
                        return $this->goBack();
                    }
                } else {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($model);
                }
            }
        } else {
            throw new HttpException(404 ,'Page not found');
        }
    }

    public function actionQuit()
    {
        Yii::$app->customer->logout();

        return $this->goHome();
    }


    public function actionCatalog()
    {
        //$this->layout = 'catalog';
        $belongings = Belonging::find()->all();
        return $this->render('catalog',[
            'belongings' => $belongings
        ]);
    }

    public function actionPrice($sort = 'created_at')
    {
        $supplies = Supply::find()->all();
        $belongings = Belonging::find()->all();
        $categories = $this->getList();
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort->enableMultiSort = true;
        $dataProvider->setSort([
            'defaultOrder' => [
                'stock' => SORT_DESC,
                $sort => SORT_DESC
            ]
        ]);

        return $this->render('test-price', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'supplies' => $supplies,
            'belongings' => $belongings,
            'categories' => $categories,
        ]);
    }

    public static function getList()
    {
        $data = Category::find()
            ->select(['id', 'parent_id', 'name'])
            ->orderBy(['parent_id' => SORT_ASC, 'name' => SORT_ASC])
            ->asArray()
            ->all();

        $sort = new SortList([
            'data' => $data,
            'prefix' => '------',
        ]);
        $sortList = ArrayHelper::map($sort->getList(), 'id', 'name');
        return $sortList;
    }

    public function actionRegister()
    {
        if(!Yii::$app->customer->isGuest) {
            return $this->goHome();
        }

        $model = new SignupForm();
        $managers = Manager::find()->all();
        $groups = Category::find()->where(['parent_id' => 0])->orWhere(['parent_id' => null])->orderBy(['name' => SORT_ASC])->all();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    Yii::$app->myMail->MailAdminInform(
                        $user,
                        'new_customer_admin_inform',
                        'Регистрация нового пользователя'
                    );
                    /*Yii::$app->my->MailCustomer(
                        $user,
                        'new_customer_welcome',
                        'Регистрация на сайте TOS Опт'
                    );*/
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
            'groups' => $groups,
            'managers' => $managers,
        ]);
    }


    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionChangeCurrency(){
        if (Yii::$app->request->isAjax) {
            $currency_id = $_GET['id'];
            $currency = Currency::findOne($currency_id);
            Yii::$app->my->start($currency->id);
            return Yii::$app->request->referrer
                ? $this->redirect(Yii::$app->request->referrer)
                : $this->goHome();
        }
    }

    public function actionChangeShipping(){
        if (Yii::$app->request->isAjax) {
            $shipping_id = $_GET['id'];
            $shipping = Shipping::findOne($shipping_id);
            Yii::$app->my->start(0, $shipping->id);
            return Yii::$app->request->referrer
                ? $this->redirect(Yii::$app->request->referrer)
                : $this->goHome();
        }
    }

    public function actionCallMe() {
        $model = new CallMe();
        if ($model->load(Yii::$app->request->post())) {
            $model->answered = 0;
            $model->created_at = date('U');

            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Спасибо! В ближайшее время с вами свяжется менеджер');

            } else {
                Yii::$app->session->setFlash('error', 'Упс... Произошла ошибка, попробуйте еще раз');
            }
            Yii::$app->myMail->MailAdminInform($model, 'call_me_admin_inform', 'Заявка на перезвон');

            $return_url = Yii::$app->request->referrer;
            if($return_url!=NULL){
                return $this->redirect($return_url);
            }
            else{
                return $this->goBack();
            }
        }
    }
}

frontend/views/belonging/_list.php
<?php
use yii\helpers\Html;
?>
<div class="image">
    <?=
    (isset($model->image->src)
        ? Html::a(
            Html::img('/image/catalog/Product/' . $model->id . '/thumb_' . $model->image->src),
            ['/product/index', 'product_id' => $model->id]

        )
        : Html::a(
            Html::img(Yii::getAlias('@mysite') . '/image/design/no-product-image.jpg'),
            ['/product/index', 'product_id' => $model->id]

        )
    )
    ?>
</div>
<div class="product-body">
    <div class="name"><?=$model->name?></div>
    <div class="info">
        <table class="table">
            <tbody>
            <tr>
                <td>Принадлежность: </td>
                <td><?=$model->belonging->name?></td>
            </tr>
            <tr>
                <td>Мин. заказ: </td>
                <td><?=$model->minimum?></td>
            </tr>
            <tr>
                <td>Вес: </td>
                <td><?=$model->weight?></td>
            </tr>
            <tr>
                <td>Цена: </td>
                <td><b class="text-danger price"><?=Yii::$app->my->conversion($model->price, $model->belonging_id, $model->weight)?></b></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="buy">
        <?=Html::a(
            'Подробнее',
            ['/product/index', 'product_id' => $model->id],
            [
                'class' => 'btn btn-tos pull-left'
            ]

        )?>
        <?=($model->stock
            ? ($model->options
                ? Html::a(
                    "<i class=\"glyphicon glyphicon-shopping-cart\"></i>&nbsp;Купить",
                    ['/product/index', 'product_id' => $model->id],
                    [
                        'class' => 'btn btn-ytos pull-right',
                        'data-id' => $model->id,
                        'data-quantity' => $model->minimum,
                    ]
                )
                : Html::a(
                "<i class=\"glyphicon glyphicon-shopping-cart\"></i>&nbsp;Купить",
                    ['/cart/add', 'id' => $model->id, 'quantity' => $model->minimum],
                    [
                        'class' => 'btn btn-ytos add-into-cart pull-right',
                        'data-id' => $model->id,
                        'data-quantity' => $model->minimum,
                    ]
                )
            )
            : Html::button(
                "<i class=\"glyphicon glyphicon-shopping-cart\"></i>&nbsp;Нет в наличии",
                //['/cart/add', 'id' => $model->id, 'quantity' => $model->minimum],
                [
                    'class' => 'btn btn-ytos pull-right',
                    'data-id' => $model->id,
                    'data-quantity' => $model->minimum,
                    'disabled' => 1,
                ]
            )
        )?>
        <div class="clear"></div>
    </div>
</div>

frontend/views/belonging/index.php
<?php

use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

if (!$category){
    $this->title = $belonging->meta_t;
    $this->registerMetaTag([
        'name' => 'keywords',
        'content' => $belonging->meta_k,
    ]);
    $this->registerMetaTag([
        'name' => 'description',
        'content' => $belonging->meta_d,
    ]);
    $this->params['breadcrumbs'][] = ['label' => 'Каталог', 'url' => ['/site/catalog']];
    $this->params['breadcrumbs'][] = $this->title;
    $this->params['main-header'] = $belonging->meta_h1;
}else{
    $this->title = $category->meta_t;
    $this->registerMetaTag([
        'name' => 'keywords',
        'content' => $category->meta_k,
    ]);
    $this->registerMetaTag([
        'name' => 'description',
        'content' => $category->meta_d,
    ]);
    $this->params['breadcrumbs'][] = ['label' => 'Каталог', 'url' => ['/site/catalog']];
    $this->params['breadcrumbs'][] = ['label' => $belonging->name, 'url' => ['/belonging/index', 'belonging_id' => $belonging->id]];
    if ($parents){
        foreach ($parents as $parent) {
            $this->params['breadcrumbs'][] = ['label' => $parent['name'], 'url' => ['', 'belonging_id' => $belonging->id, 'category_id' => $parent['id']]];
        }
    }
    $this->params['breadcrumbs'][] = $this->title;
    $this->params['main-header'] = $category->meta_h1;
}
?>
<div class="belonging-index">
    <?php

    echo ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_list',
        'itemOptions' => [
            'tag' => 'div',
            'class' => 'product',
        ],
        'options' => [
            'tag' => 'div',
            'class' => 'products',
        ],

        'layout' => "{items}\n{pager}",
        'summary' => 'Показано {count} из {totalCount}',
        'summaryOptions' => [
            'tag' => 'div',
            'class' => 'summary'
        ],
    ]);
    ?>

</div>